// Load test: chat burst across N clusters of 8 members.
// Simulates the core live-user paths: send_message (write + push fan-out),
// mark_cluster_read (read receipts), get_my_notifications /
// get_unread_notification_count (badge + center), plus one realtime
// subscriber per cluster counting message inserts.
//
// Safety:
//   - Defaults to the LOCAL stack (resolves via `supabase status`, same as
//     scripts/seed-demo.mjs). To run against staging you must set
//     LOAD_SUPABASE_URL + LOAD_ANON_KEY + LOAD_SERVICE_ROLE_KEY AND
//     LOAD_CONFIRM=staging. Anything else aborts.
//   - Creates users as load-<run>-<i>@load.test and deletes them + the
//     clusters afterwards (skip with LOAD_KEEP=1).
//   - Stays under the 0138 rate limits: 60 messages/hour/user. Default is
//     5 messages per user, well under budget.
//
// Usage:
//   node scripts/load/chat-burst.mjs
//   LOAD_CLUSTERS=25 LOAD_MSGS_PER_USER=5 LOAD_CONCURRENCY=16 node scripts/load/chat-burst.mjs
//   npm run load:chat
//
// Env:
//   LOAD_CLUSTERS (default 25), LOAD_MSGS_PER_USER (default 5),
//   LOAD_CONCURRENCY (default 16), LOAD_PUSH_TOKENS (default 0: register N
//   fake Expo tokens so push_outbox fills), LOAD_KEEP=1 to skip cleanup,
//   LOAD_CONFIRM=staging to allow a non-local URL.

import { randomUUID } from 'node:crypto'
import { execSync } from 'node:child_process'
import { createClient } from '@supabase/supabase-js'

const CLUSTERS = Number(process.env.LOAD_CLUSTERS ?? 25)
const MSGS_PER_USER = Number(process.env.LOAD_MSGS_PER_USER ?? 5)
const CONCURRENCY = Number(process.env.LOAD_CONCURRENCY ?? 16)
const PUSH_TOKENS = Number(process.env.LOAD_PUSH_TOKENS ?? 0)
const KEEP = process.env.LOAD_KEEP === '1'
const PASSWORD = 'load-pass-123'
const RUN = randomUUID().slice(0, 8)

function statusJson() {
  try {
    return JSON.parse(execSync('npx supabase status -o json', { encoding: 'utf8' }))
  } catch {
    return {}
  }
}

function resolveConfig() {
  const s = statusJson()
  const url =
    process.env.LOAD_SUPABASE_URL ?? s.API_URL ?? 'http://127.0.0.1:54321'
  const anonKey = process.env.LOAD_ANON_KEY ?? s.PUBLISHABLE_KEY ?? s.ANON_KEY
  const serviceRole =
    process.env.LOAD_SERVICE_ROLE_KEY ?? s.SERVICE_ROLE_KEY
  const explicitRemote = Boolean(process.env.LOAD_SUPABASE_URL)
  if (explicitRemote && process.env.LOAD_CONFIRM !== 'staging') {
    throw new Error(
      'Refusing to load-test a non-local URL without LOAD_CONFIRM=staging.',
    )
  }
  if (!url || !anonKey || !serviceRole) {
    throw new Error(
      'Could not resolve Supabase URL/anon/service_role. Run `supabase start` or set LOAD_SUPABASE_URL + LOAD_ANON_KEY + LOAD_SERVICE_ROLE_KEY.',
    )
  }
  return { url, anonKey, serviceRole, remote: explicitRemote }
}

function percentile(sorted, p) {
  if (!sorted.length) return 0
  return sorted[Math.min(sorted.length - 1, Math.floor((p / 100) * sorted.length))]
}

async function mapPool(items, size, fn) {
  const results = new Array(items.length)
  let next = 0
  let failed = 0
  async function worker() {
    while (next < items.length) {
      const i = next++
      try {
        results[i] = await fn(items[i], i)
      } catch (err) {
        failed++
        results[i] = { error: err?.message ?? String(err) }
      }
    }
  }
  await Promise.all(Array.from({ length: Math.min(size, items.length) }, worker))
  return { results, failed }
}

async function main() {
  const totalUsers = CLUSTERS * 8
  const totalMsgs = totalUsers * MSGS_PER_USER
  console.log(
    `[load] run=${RUN} clusters=${CLUSTERS} users=${totalUsers} msgs/user=${MSGS_PER_USER} total_msgs=${totalMsgs} concurrency=${CONCURRENCY} push_tokens=${PUSH_TOKENS}`,
  )
  if (MSGS_PER_USER > 50) {
    throw new Error('MSGS_PER_USER too high: keep under the 60/hour rate limit.')
  }

  const { url, anonKey, serviceRole, remote } = resolveConfig()
  console.log(`[load] target=${url} remote=${remote ? 'yes (staging confirmed)' : 'no (local)'}`)

  const admin = createClient(url, serviceRole, {
    auth: { autoRefreshToken: false, persistSession: false },
  })
  const mkAuthed = () =>
    createClient(url, anonKey, { auth: { persistSession: false } })

  // Sign in with password; on captcha-protected remotes (staging/prod with
  // Turnstile enforced) fall back to a magiclink generated by the admin API,
  // which does not require a captcha token.
  const sleep = (ms) => new Promise((r) => setTimeout(r, ms))
  async function withRetry(fn, label) {
    for (let attempt = 1; attempt <= 8; attempt++) {
      try {
        return await fn()
      } catch (err) {
        const msg = err?.message ?? String(err)
        if (/rate limit|429|over_request|too many/i.test(msg) && attempt < 8) {
          const wait = 5000 * attempt
          console.log(`[load] ${label} rate-limited, retry ${attempt}/8 after ${wait}ms`)
          await sleep(wait)
          continue
        }
        throw err
      }
    }
  }
  async function signIn(client, email) {
    const { error } = await withRetry(
      async () => {
        const r = await client.auth.signInWithPassword({ email, password: PASSWORD })
        if (r.error && /rate limit|429|over_request|too many/i.test(r.error.message)) throw r.error
        return r
      },
      `signin ${email}`,
    )
    if (!error) return
    if (!error.message.includes('captcha')) throw error
    const otp = await withRetry(
      async () => {
        const { data: link, error: linkErr } = await admin.auth.admin.generateLink({
          type: 'magiclink',
          email,
        })
        if (linkErr) throw linkErr
        const o = link?.properties?.email_otp
        if (!o) throw new Error('magiclink did not return an OTP')
        return o
      },
      `magiclink ${email}`,
    )
    const { error: verifyErr } = await withRetry(
      async () => {
        const r = await client.auth.verifyOtp({ email, token: otp, type: 'magiclink' })
        if (r.error && /rate limit|429|over_request|too many/i.test(r.error.message)) throw r.error
        return r
      },
      `verify ${email}`,
    )
    if (verifyErr) throw verifyErr
  }

  // 1. Setup: users + onboard + clusters (timed separately from the burst).
  const tSetup = Date.now()
  const users = []
  for (let i = 0; i < totalUsers; i++) {
    const email = `load-${RUN}-${i}@load.test`
    const { data, error } = await withRetry(
      async () => {
        const r = await admin.auth.admin.createUser({ email, password: PASSWORD, email_confirm: true })
        if (r.error && /rate limit|429|over_request|too many/i.test(r.error.message)) throw r.error
        return r
      },
      `createUser ${email}`,
    )
    if (error) throw error
    await admin.from('profiles').update({
      display_name: `Load ${i}`,
      dob: '1992-03-14',
      onboarding_completed_at: new Date().toISOString(),
    }).eq('id', data.user.id)
    const client = mkAuthed()
    await signIn(client, email)
    users.push({ id: data.user.id, email, client })
    // Throttle setup on remotes: Supabase Auth rate-limits user creation.
    if (remote) {
      if (i % 10 === 9) await sleep(5000)
      else await sleep(300)
    }
    if ((i + 1) % 50 === 0) console.log(`[load] setup users ${i + 1}/${totalUsers}`)
  }

  const clusterIds = []
  for (let c = 0; c < CLUSTERS; c++) {
    const members = users.slice(c * 8, c * 8 + 8).map((u) => u.id)
    const { data, error } = await admin.from('clusters').insert({
      name: `Load ${RUN}-${c}`,
      matching_mode: 'open_mix',
      mode_label: 'Open Mix',
      queue_key: 'open',
      status: 'active',
      introductions_completed_at: new Date().toISOString(),
    }).select('id').single()
    if (error) throw error
    const { error: mErr } = await admin.from('cluster_members').insert(
      members.map((user_id) => ({ cluster_id: data.id, user_id })),
    )
    if (mErr) throw mErr
    clusterIds.push(data.id)
  }
  console.log(`[load] setup done in ${Date.now() - tSetup}ms (${clusterIds.length} clusters)`)

  // 1b. Push tokens: register fake Expo tokens for the first N users via the
  // real client RPC, so plain-chat fan-out writes per-token push_outbox rows.
  // Fake tokens fail at the Expo API (deleted as DeviceNotRegistered on first
  // pump), but they prove the DB fan-out + pump drain under burst load.
  if (PUSH_TOKENS > 0) {
    const withTokens = users.slice(0, Math.min(PUSH_TOKENS, users.length))
    const { failed } = await mapPool(withTokens, CONCURRENCY, async (u, i) => {
      const { error } = await u.client.rpc('register_push_token', {
        p_expo_push_token: `ExponentPushToken[load-${RUN}-${i}]`,
      })
      if (error) throw error
    })
    console.log(`[load] registered ${withTokens.length - failed}/${withTokens.length} push tokens`)
    if (failed) throw new Error('push token registration failed')
  }

  // 2. Realtime: one subscriber per cluster counting inserts. Wait for
  // SUBSCRIBED before bursting, otherwise early messages are missed.
  let rtReceived = 0
  const rtClients = []
  await Promise.all(clusterIds.map(async (cid, c) => {
    const rc = mkAuthed()
    // Each subscriber must auth as a member of its own cluster: realtime
    // postgres_changes respects RLS, so a non-member receives nothing.
    await signIn(rc, users[c * 8].email)
    rtClients.push(rc)
    await new Promise((resolve) => {
      const timer = setTimeout(resolve, 10000)
      rc.channel(`load-${RUN}-${cid}`)
        .on(
          'postgres_changes',
          { event: 'INSERT', schema: 'public', table: 'messages', filter: `cluster_id=eq.${cid}` },
          () => { rtReceived++ },
        )
        .subscribe((status) => {
          if (status === 'SUBSCRIBED') {
            clearTimeout(timer)
            resolve()
          }
        })
    })
  }))

  // 3. Burst: every user sends MSGS_PER_USER messages to their cluster.
  const jobs = []
  users.forEach((u, i) => {
    const cid = clusterIds[Math.floor(i / 8)]
    for (let m = 0; m < MSGS_PER_USER; m++) {
      jobs.push({ u, cid, m })
    }
  })
  // Deterministic shuffle so bursts interleave across clusters.
  for (let i = jobs.length - 1; i > 0; i--) {
    const j = (i * 2654435761 + 97) % (i + 1)
    ;[jobs[i], jobs[j]] = [jobs[j], jobs[i]]
  }

  const sendLat = []
  let sendErr = 0
  let rateLimited = 0
  const tBurst = Date.now()
  await mapPool(jobs, CONCURRENCY, async ({ u, cid, m }) => {
    const t = Date.now()
    const { error } = await u.client.rpc('send_message', {
      p_cluster_id: cid,
      p_content: `load ${RUN} msg ${m} from ${u.email}`,
    })
    sendLat.push(Date.now() - t)
    if (error) {
      sendErr++
      if (error.message.includes('rate_limited')) rateLimited++
      else console.error(`[load] send error: ${error.message}`)
    }
  })
  const burstMs = Date.now() - tBurst
  sendLat.sort((a, b) => a - b)

  // 4. Read paths: every user marks read + fetches badge + center.
  const readLat = []
  let readErr = 0
  const tRead = Date.now()
  await mapPool(users, CONCURRENCY, async (u, i) => {
    const cid = clusterIds[Math.floor(i / 8)]
    const t = Date.now()
    const { error: e1 } = await u.client.rpc('mark_cluster_read', { p_cluster_id: cid })
    const { error: e2 } = await u.client.rpc('get_unread_notification_count')
    const { error: e3 } = await u.client.rpc('get_my_notifications')
    readLat.push(Date.now() - t)
    if (e1 || e2 || e3) {
      readErr++
      console.error(`[load] read error: ${e1?.message ?? e2?.message ?? e3?.message}`)
    }
  })
  readLat.sort((a, b) => a - b)

  // Give realtime a moment to deliver, then report. Remote needs longer.
  await new Promise((r) => setTimeout(r, remote ? 15000 : 5000))

  console.log('--- load results ---')
  console.log(`setup_ms=${Date.now() - tSetup} burst_ms=${burstMs} read_ms=${Date.now() - tRead}`)
  console.log(`sent=${totalMsgs - sendErr}/${totalMsgs} send_errors=${sendErr} rate_limited=${rateLimited}`)
  console.log(`send p50=${percentile(sendLat, 50)}ms p95=${percentile(sendLat, 95)}ms p99=${percentile(sendLat, 99)}ms`)
  console.log(`read p50=${percentile(readLat, 50)}ms p95=${percentile(readLat, 95)}ms p99=${percentile(readLat, 99)}ms read_errors=${readErr}`)
  console.log(`realtime_received=${rtReceived}/${totalMsgs - sendErr} subscribers=${rtClients.length}`)
  for (const rc of rtClients) await rc.removeAllChannels()

  // 5. Outbox lag: queued rows plus all statuses (staging pump drains
  // queued -> sent/failed within a minute, so queued=0 alone is ambiguous).
  const { data: pushRows } = await admin.from('push_outbox').select('status').in('user_id', users.map((u) => u.id))
  const pushByStatus = {}
  for (const r of pushRows ?? []) pushByStatus[r.status] = (pushByStatus[r.status] ?? 0) + 1
  const { count: emailQueued } = await admin.from('outbound_emails').select('id', { count: 'exact', head: true }).eq('status', 'queued')
  console.log(`push_outbox=${JSON.stringify(pushByStatus)} outbound_emails_queued=${emailQueued ?? '?'}`)

  console.log('--- thresholds (fail if exceeded) ---')
  const fails = []
  if (sendErr > totalMsgs * 0.01) fails.push(`send error rate >1% (${sendErr}/${totalMsgs})`)
  if (percentile(sendLat, 99) > 3000) fails.push(`send p99 >3000ms (${percentile(sendLat, 99)}ms)`)
  if (percentile(readLat, 99) > 3000) fails.push(`read p99 >3000ms (${percentile(readLat, 99)}ms)`)
  if (rtReceived < (totalMsgs - sendErr) * 0.95) fails.push(`realtime delivery <95% (${rtReceived}/${totalMsgs - sendErr})`)
  if (fails.length) {
    console.error(`LOAD FAIL:\n- ${fails.join('\n- ')}`)
  } else {
    console.log('LOAD PASS')
  }

  // 6. Cleanup.
  if (!KEEP) {
    const userIds = users.map((u) => u.id)
    await admin.from('clusters').delete().in('id', clusterIds)
    for (const id of userIds) {
      const { error } = await admin.auth.admin.deleteUser(id)
      if (error && !error.message.includes('not found')) throw error
    }
    console.log('[load] cleaned up users + clusters')
  } else {
    console.log('[load] kept fixtures (LOAD_KEEP=1)')
  }
  if (fails.length) process.exitCode = 1
}

main().catch((err) => {
  console.error(`[load] fatal: ${err?.message ?? err}`)
  process.exitCode = 1
})
