export const colors = {
  surface: '#fff8f6',
  surfaceDim: '#e5d7d2',
  surfaceLowest: '#ffffff',
  surfaceLow: '#fff1ec',
  surfaceContainer: '#faebe6',
  surfaceHigh: '#f4e5e0',
  surfaceHighest: '#eedfda',
  onSurface: '#211a17',
  onSurfaceVariant: '#56423c',
  inverseSurface: '#372f2b',
  inverseOnSurface: '#fdeee8',
  outline: '#8a726b',
  outlineVariant: '#ddc0b8',
  primary: '#9d3d1c',
  onPrimary: '#ffffff',
  primaryContainer: '#bd5532',
  inversePrimary: '#ffb59e',
  secondary: '#615e58',
  onSecondary: '#ffffff',
  secondaryContainer: '#e7e2da',
  tertiary: '#695851',
  onTertiary: '#ffffff',
  tertiaryContainer: '#837069',
  error: '#ba1a1a',
  onError: '#ffffff',
  errorContainer: '#ffdad6',
  background: '#fff8f6',
  onBackground: '#211a17',
  shadowColor: '#9d3d1c',
} as const

export const darkColors: Record<keyof typeof colors, string> = {
  surface: '#1a1a1a',
  surfaceDim: '#1a1a1a',
  surfaceLowest: '#111111',
  surfaceLow: '#1f1f1f',
  surfaceContainer: '#222222',
  surfaceHigh: '#2a2a2a',
  surfaceHighest: '#333333',
  onSurface: '#fcf9f2',
  onSurfaceVariant: '#8a847e',
  inverseSurface: '#fcf9f2',
  inverseOnSurface: '#1a1a1a',
  outline: '#6f6a64',
  outlineVariant: '#2a2a2a',
  primary: '#ff8a5c',
  onPrimary: '#3a0b00',
  primaryContainer: '#8f2f0d',
  inversePrimary: '#9d3d1c',
  secondary: '#cbc6be',
  onSecondary: '#33312c',
  secondaryContainer: '#4a4842',
  tertiary: '#d9c2b9',
  onTertiary: '#3b2d27',
  tertiaryContainer: '#53433d',
  error: '#ffb4ab',
  onError: '#690005',
  errorContainer: '#93000a',
  background: '#1a1a1a',
  onBackground: '#fcf9f2',
  shadowColor: '#000000',
}

export const radii = {
  sm: 4,
  md: 12,
  lg: 16,
  xl: 24,
  xxl: 32,
  pill: 9999,
} as const

export const spacing = {
  unit: 8,
  containerMargin: 24,
  gutter: 16,
  sectionGap: 40,
} as const

/** Raised-card treatment: elevation for the lift, shadow tint pulled from the
 * active theme (terracotta in light, neutral black in dark). */
export const shadowShape = {
  elevation: 2,
  shadowOpacity: 0.14,
  shadowRadius: 10,
  shadowOffset: { width: 0, height: 4 },
} as const
